name: .NET Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Add this permissions block!
    permissions:
      checks: write # Allows the action to create the Check Run report
      # Optional: Add pull-requests: write if you want annotations on PR files
      # pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Or your target version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      id: tests
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      continue-on-error: true # Keep this if you want the report even on failure

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: xUnit Tests
        path: '**/test-results.trx'
        reporter: dotnet-trx
        fail-on-error: 'true'
        # Keep your other options here:
        path-replace-backslashes: false
        list-suites: all
        list-tests: all
        max-annotations: 10
        fail-on-empty: true
        only-summary: false
        token: ${{ secrets.GITHUB_TOKEN }} # Usually implied, but doesn't hurt to be explicit if needed