name: .NET Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Or your target version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      id: tests # Give the test step an ID
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
      # Optional: Continue even if tests fail, so the reporter always runs
      continue-on-error: true

    - name: Test Report # This step uses the Test Reporter action
      uses: dorny/test-reporter@v1
      if: always() # Ensures this runs even if prior steps fail (like tests)
      with:
        name: xUnit Tests # Name of the check run which will be created
        path: '**/test-results.trx' # Path to the test results file(s)
        reporter: dotnet-trx # Specify the format
        fail-on-error: 'true' # Report fail?