# .github/workflows/dotnet.yml

name: .NET Build, Test, and Update Detailed README Report

on:
  push:
    branches:
      - main

jobs:
  build-test-readme:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      id: tests
      run: dotnet test --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx"
      continue-on-error: true

    - name: Generate Test Report Summary (UI)
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: xUnit Tests (UI Report)
        path: '**/test-results.trx'
        reporter: dotnet-trx
        fail-on-error: 'true'

    - name: Parse Test Results and Update README with Detailed Report
      if: always()  # <-- ✅ this is the fix
      shell: pwsh
      run: |
        # (your PowerShell script remains exactly the same)
        # just keeping this short for clarity
        # the only change is 'if: always()'

    - name: Commit and Push README changes
      if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        readme_file="README.md"
        if git diff --quiet HEAD -- "$readme_file"; then
          echo "No changes detected in $readme_file."
          exit 0
        fi
        echo "Changes detected in $readme_file. Committing..."
        git add "$readme_file"
        git commit -m "docs: Update detailed test results report in README [skip ci]"
        git push origin main
