name: .NET 9 Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run Tests (human-readable + TRX)
        run: |
          dotnet test --logger "trx;LogFileName=test-results.trx" --logger "console;verbosity=normal" > test-results.log

      - name: Upload TRX as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/*.trx'

      - name: Update README.md with test results
        uses: unfor19/replacer-action@v1
        with:
          src-file-path: "test-results.log"
          dst-file-path: "README.md"
          start-value: "<!-- test_results_start -->"
          end-value: "<!-- test_results_end -->"

      - name: Commit and Push README.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update README with test results"
          git push
